### ISSUE TITLE
About the results of 'testOnlyClusterInitialization'

### ISSUE THREAD

**Issue by shenyuanyuan** [elieJalbout/Clustering-with-Deep-learning#1]
I run the code in MNIST with the default network structure given in the file 'mnist.json'. Specifically, for Autoencoder I use the command '' python main.py -d MNIST -a 1 --pretrain 500 ". However, I can only get the best result (0.607) for cluster accuracy. The result is far from the reported result (~ 0.760). What's the possible problem? Any suggestions?

**Comment by rezacsedu** [comment]
@shenyuanyuan, but when I try to start the training on MNIST witth the command "$ python main.py -d MNIST -a 1 --pretrain 10", I experience the following error saying AttributeError: 'module' object has no attribute 'Deconv2DLayer'. However, I have configured all the dependencies. Here is the Traceback:

[05/17 02:31:58] Loading dataset
[05/17 02:31:59] Done loading dataset
[05/17 02:31:59] Creating network
Traceback (most recent call last):
File "main.py", line 160, in
testOnlyClusterInitialization(dataset_name, archs[arch_index], args.pretrain)
File "main.py", line 26, in testOnlyClusterInitialization
dcjc = DCJC(arch_copy)
File "/home/root/Downloads/Clustering-with-Deep-learning-master/network.py", line 47, in init
self.network = netbuilder.buildNetwork()
File "/home/root/Downloads/Clustering-with-Deep-learning-master/network.py", line 358, in buildNetwork
network = self.processLayer(network, layer)
File "/home/root/Downloads/Clustering-with-Deep-learning-master/network.py", line 481, in processLayer
network = lasagne.layers.Deconv2DLayer(network, num_filters=layer_definition['num_filters'], filter_size=tuple(layer_definition['filter_size']), crop=layer_definition['conv_mode'], nonlinearity=self.getNonLinearity(layer_definition['non_linearity']), name=self.getLayerName(layer_definition))
AttributeError: 'module' object has no attribute 'Deconv2DLayer'

Did you face this issue? If not, could you tell me what could be the reason?

**Comment by shenyuanyuan** [comment]
I haven't met this issue. It seems the problem of the lasagne.

**Comment by rezacsedu** [comment]
@shenyuanyuan, sorry to bother again but which version of theano and lasagne are you using? I'm using lasagne 0.2.dev1 and theano 1.0.1.
