### ISSUE TITLE
How to duplicate the results

### ISSUE THREAD

**Issue by chulaihunde** [elieJalbout/Clustering-with-Deep-learning#10]
Hi,
I am trying to duplicate the results of your paper, but cannot. Would it be possible to describe training process?

**Comment by ElieAljalbout** [comment]
Can you describe what you did and which dataset you used?

**Comment by chulaihunde** [comment]
python main.py -d="MNIST" -a=1  --pretrain=500 --cluster=50 --metrics --visualize

**Comment by MaryleenAmaizu** [comment]
I'm facing the same issue. It would be great to show with an example how to specify the arguments in the command line to run this code from start. Thanks.

**Comment by ElieAljalbout** [comment]
I suggest you try different network architectures and hyper parameters as a lot of other people have used this repository and reproduced the results successfully

**Comment by yangyuchen0340** [comment]
I faced the same issue. Actually there is a big gap (0.7 versus 0.8).
I did python main.py -d="MNIST" -a=1 --pretrain=500 --cluster=200 --metrics
You mean we need further modify the hyperparameter and network to obtain the reported results? @
