### ISSUE TITLE
new dataset

### ISSUE THREAD

**Issue by dnnguifever** [elieJalbout/Clustering-with-Deep-learning#11]
This is great work, thank you.

I have a set of new images in a folder that I would like to cluster. 
How can I get the code to work on my dataset? Do I have to put the images in some particular format? 

Thank you for your help!

**Comment by ElieAljalbout** [comment]
You don't have to change the format of the images, you just have to write functions (or optimally a class) that provides access to your data the same way the provided datasets does it and then create a json architecture file corresponding to your input format in the archs directory. The design of the network architecture is something you should think of, but the method itself is not very dependent on it.

**Comment by dnnguifever** [comment]
Forgive me, I'm new to the field. I don't know how to do all that yet. Any tips on how to do that, or resources that might help me? 
Thanks!

**Comment by ratheraarif** [comment]
i am a beginner. can you please give me a step by step procedure to run the code
