### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by dnnguifever** [elieJalbout/Clustering-with-Deep-learning#12]
rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=W, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

Have you ever seen an error like this before? 

Thanks!

**Comment by yangyuchen0340** [comment]
maybe set floatX=float32 in ~/.theanorc

**Comment by ratheraarif** [comment]
kindly give me a detailed procedure to run the code.. step by step
